# Generated by Django 4.1 on 2022-09-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_song_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="listened",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
