# Generated by Django 4.0.2 on 2022-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_listened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='listened',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
